issuer: https://oidc.local:5554

storage:
  type: memory

web:
  http: 0.0.0.0:5556
  https: 0.0.0.0:5554
  tlsCert: /etc/dex/certs/local.crt
  tlsKey: /etc/dex/certs/local.key
  allowedOrigins:
    - http://localhost:3000

staticClients:
  - id: twake-calendar
    redirectURIs:
      - 'http://localhost:3000/callback'
    name: 'Twake Calendar'
    public: true

  - id: tcalendar-side-service
    redirectURIs:
      - 'http://localhost:8000/callback'
    name: 'Twake Calendar Side Service Dev'
    secret: "secret123"

enablePasswordDB: true

oauth2:
  skipApprovalScreen: true
  responseTypes: ["code", "token", "id_token"]

staticPasswords:
  - email: "alice@linagora.com"
    hash: "$2a$12$O3NhVD9nbCYJtWAH9D0PDO23qtM9pMdn5/G6p4I.4J6qklIrYNWIG" # alice
    username: "alice"
    userID: "1"

  - email: "bob@linagora.com"
    hash: "$2a$12$Qnw3T.u.obn2wPyhX5/0v.Oi3SOn4Ittu0t2LamK1JILve4jslta6" # bob
    username: "bob"
    userID: "2"

  - email: "cedric@linagora.com"
    hash: "$2a$12$MpLqAzWJ9C.WcIGllZ.sS.LDpcwP11XC8akwuWfeK4Pu088reiRby" # cedric
    username: "cedric"
    userID: "3"
logger:
  level: "debug"