/********************************************************************
 *  As a subpart of Twake Mail, this file is edited by Linagora.    *
 *                                                                  *
 *  https://twake-mail.com/                                         *
 *  https://linagora.com                                            *
 *                                                                  *
 *  This file is subject to The Affero Gnu Public License           *
 *  version 3.                                                      *
 *                                                                  *
 *  https://www.gnu.org/licenses/agpl-3.0.en.html                   *
 *                                                                  *
 *  This program is distributed in the hope that it will be         *
 *  useful, but WITHOUT ANY WARRANTY; without even the implied      *
 *  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR         *
 *  PURPOSE. See the GNU Affero General Public License for          *
 *  more details.                                                   *
 ********************************************************************/

package com.linagora.calendar.webadmin.service;

import static org.apache.james.util.ReactorUtils.DEFAULT_CONCURRENCY;

import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.Predicate;

import org.apache.commons.lang3.StringUtils;
import org.apache.james.core.Username;
import org.apache.james.task.Task;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.inject.Inject;
import com.linagora.calendar.dav.CalDavClient;
import com.linagora.calendar.storage.CalendarURL;
import com.linagora.calendar.storage.booking.BookingLinkPublicId;
import com.linagora.calendar.storage.event.EventFields;
import com.linagora.calendar.storage.eventsearch.CalendarSearchService;
import com.linagora.calendar.storage.eventsearch.EventSearchQuery;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Deletes all events that were generated by a given booking link, relying on the
 * {@code X-OPENPAAS-BOOKING-LINK} search criterion (see issue #867) to locate them and on the
 * CalDAV backend to actually remove them.
 *
 * <p>An optional {@code since} instant restricts the deletion to events created (or last modified)
 * at or after that instant, based on the event {@code DTSTAMP}. This is convenient for a partial
 * clean up, e.g. after a booking link has been compromised at a known point in time.
 */
public class BookingLinkEventDeletionService {

    private static final Logger LOGGER = LoggerFactory.getLogger(BookingLinkEventDeletionService.class);

    private static final int SEARCH_PAGE_SIZE = EventSearchQuery.MAX_LIMIT;
    private static final String ICS_EXTENSION = ".ics";

    public static class Context {
        private final AtomicLong deleted;
        private final AtomicLong failed;

        public Context() {
            this.deleted = new AtomicLong();
            this.failed = new AtomicLong();
        }

        public record Snapshot(long deleted, long failed) {
        }

        void increaseDeleted() {
            deleted.incrementAndGet();
        }

        void increaseFailed() {
            failed.incrementAndGet();
        }

        public Snapshot snapshot() {
            return new Snapshot(deleted.get(), failed.get());
        }
    }

    private record Page(List<EventFields> events, int nextOffset) {
    }

    private final CalendarSearchService searchService;
    private final CalDavClient calDavClient;

    @Inject
    public BookingLinkEventDeletionService(CalendarSearchService searchService, CalDavClient calDavClient) {
        this.searchService = searchService;
        this.calDavClient = calDavClient;
    }

    public Mono<Task.Result> deleteEvents(Username username,
                                          CalendarURL calendarUrl,
                                          BookingLinkPublicId bookingLinkPublicId,
                                          Optional<Instant> since,
                                          Context context) {
        LOGGER.info("Deleting events of booking link {} in calendar {} for user {}{}",
            bookingLinkPublicId.value(), calendarUrl.asUri(), username.asString(),
            since.map(instant -> " since " + instant).orElse(""));

        return searchAllEvents(calendarUrl, bookingLinkPublicId)
            .filter(sinceFilter(since))
            .flatMap(event -> deleteEvent(username, context, event), DEFAULT_CONCURRENCY)
            .reduce(Task.Result.COMPLETED, Task::combine)
            .onErrorResume(e -> {
                LOGGER.error("Failed to delete events of booking link {} for user {}",
                    bookingLinkPublicId.value(), username.asString(), e);
                return Mono.just(Task.Result.PARTIAL);
            });
    }

    private Flux<EventFields> searchAllEvents(CalendarURL calendarUrl, BookingLinkPublicId bookingLinkPublicId) {
        return searchPage(calendarUrl, bookingLinkPublicId, EventSearchQuery.OFFSET_INITIAL)
            .expand(page -> {
                if (page.events().size() < SEARCH_PAGE_SIZE) {
                    return Mono.empty();
                }
                return searchPage(calendarUrl, bookingLinkPublicId, page.nextOffset());
            })
            .flatMapIterable(Page::events);
    }

    private Mono<Page> searchPage(CalendarURL calendarUrl, BookingLinkPublicId bookingLinkPublicId, int offset) {
        EventSearchQuery query = EventSearchQuery.builder()
            .query(StringUtils.EMPTY)
            .calendars(calendarUrl)
            .bookingLink(bookingLinkPublicId)
            .limit(SEARCH_PAGE_SIZE)
            .offset(offset)
            .build();

        return searchService.search(query)
            .collectList()
            .map(events -> new Page(events, offset + SEARCH_PAGE_SIZE));
    }

    private Predicate<EventFields> sinceFilter(Optional<Instant> since) {
        return since.<Predicate<EventFields>>map(instant ->
                event -> event.dtStamp() != null && !event.dtStamp().isBefore(instant))
            .orElse(event -> true);
    }

    private Mono<Task.Result> deleteEvent(Username username, Context context, EventFields event) {
        String eventId = event.resourceName()
            .map(name -> StringUtils.removeEnd(name, ICS_EXTENSION))
            .orElseGet(() -> event.uid().value());

        return calDavClient.deleteCalendarEvent(username, event.calendarURL(), eventId)
            .doOnSuccess(any -> context.increaseDeleted())
            .thenReturn(Task.Result.COMPLETED)
            .onErrorResume(e -> {
                LOGGER.warn("Failed to delete event {} in calendar {} for user {}",
                    eventId, event.calendarURL().asUri(), username.asString(), e);
                context.increaseFailed();
                return Mono.just(Task.Result.PARTIAL);
            });
    }
}
