/********************************************************************
 *  As a subpart of Twake Mail, this file is edited by Linagora.    *
 *                                                                  *
 *  https://twake-mail.com/                                         *
 *  https://linagora.com                                            *
 *                                                                  *
 *  This file is subject to The Affero Gnu Public License           *
 *  version 3.                                                      *
 *                                                                  *
 *  https://www.gnu.org/licenses/agpl-3.0.en.html                   *
 *                                                                  *
 *  This program is distributed in the hope that it will be         *
 *  useful, but WITHOUT ANY WARRANTY; without even the implied      *
 *  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR         *
 *  PURPOSE. See the GNU Affero General Public License for          *
 *  more details.                                                   *
 ********************************************************************/

package com.linagora.calendar.webadmin.service;

import static org.apache.james.util.ReactorUtils.DEFAULT_CONCURRENCY;

import java.time.Instant;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import org.apache.james.core.Username;
import org.apache.james.task.Task;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.inject.Inject;
import com.linagora.calendar.api.CalendarUtil;
import com.linagora.calendar.dav.CalDavClient;
import com.linagora.calendar.dav.dto.CalendarReportXmlResponse;
import com.linagora.calendar.dav.dto.CalendarReportXmlResponse.CalendarObject;
import com.linagora.calendar.dav.model.CalendarQuery;
import com.linagora.calendar.storage.CalendarURL;
import com.linagora.calendar.storage.booking.BookingLinkPublicId;
import com.linagora.calendar.storage.event.EventParseUtils;

import net.fortuna.ical4j.model.Calendar;
import net.fortuna.ical4j.model.Component;
import net.fortuna.ical4j.model.Property;
import net.fortuna.ical4j.model.component.VEvent;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Deletes all events that were generated by a given booking link.
 *
 * <p>Rather than relying on the search index (whose offset-based pagination is unstable while we are
 * concurrently deleting the very events we are paging over), this service lists the events straight
 * from the CalDAV backend through a RFC 4791 {@code calendar-query} REPORT. CalDAV is the source of
 * truth, the listing is taken as a single consistent snapshot and the {@code X-OPENPAAS-BOOKING-LINK}
 * property (see issue #867) is matched on the returned calendar data.
 *
 * <p>An optional {@code since} instant restricts the deletion to events created (or last modified)
 * at or after that instant, based on the event {@code DTSTAMP}. This is convenient for a partial
 * clean up, e.g. after a booking link has been compromised at a known point in time.
 */
public class BookingLinkEventDeletionService {

    private static final Logger LOGGER = LoggerFactory.getLogger(BookingLinkEventDeletionService.class);

    private static final String BOOKING_LINK_PROPERTY = "X-OPENPAAS-BOOKING-LINK";

    public static class Context {
        private final AtomicLong deleted;
        private final AtomicLong failed;

        public Context() {
            this.deleted = new AtomicLong();
            this.failed = new AtomicLong();
        }

        public record Snapshot(long deleted, long failed) {
        }

        void increaseDeleted() {
            deleted.incrementAndGet();
        }

        void increaseFailed() {
            failed.incrementAndGet();
        }

        public Snapshot snapshot() {
            return new Snapshot(deleted.get(), failed.get());
        }
    }

    public record DeletionRequest(Username username,
                                  CalendarURL calendarUrl,
                                  BookingLinkPublicId bookingLinkPublicId,
                                  Optional<Instant> since) {
    }

    private final CalDavClient calDavClient;

    @Inject
    public BookingLinkEventDeletionService(CalDavClient calDavClient) {
        this.calDavClient = calDavClient;
    }

    public Mono<Task.Result> deleteEvents(DeletionRequest request, Context context) {
        Username username = request.username();
        BookingLinkPublicId bookingLinkPublicId = request.bookingLinkPublicId();

        LOGGER.info("Deleting events of booking link {} in calendar {} for user {}{}",
            bookingLinkPublicId.value(), request.calendarUrl().asUri(), username.asString(),
            request.since().map(instant -> " since " + instant).orElse(""));

        return listBookingLinkEvents(request)
            .flatMap(eventPathId -> deleteEvent(username, request.calendarUrl(), context, eventPathId), DEFAULT_CONCURRENCY)
            .reduce(Task.Result.COMPLETED, Task::combine)
            .onErrorResume(e -> {
                LOGGER.error("Failed to delete events of booking link {} for user {}",
                    bookingLinkPublicId.value(), username.asString(), e);
                return Mono.just(Task.Result.PARTIAL);
            });
    }

    private Flux<String> listBookingLinkEvents(DeletionRequest request) {
        return calDavClient.calendarQueryReportXml(request.username(), request.calendarUrl(), CalendarQuery.ofFilters())
            .flatMapIterable(CalendarReportXmlResponse::extractCalendarObjects)
            .filter(calendarObject -> belongsToBookingLink(calendarObject, request.bookingLinkPublicId(), request.since()))
            .map(CalendarObject::eventPathId);
    }

    private boolean belongsToBookingLink(CalendarObject calendarObject, BookingLinkPublicId bookingLinkPublicId, Optional<Instant> since) {
        try {
            Calendar calendar = CalendarUtil.parseIcs(calendarObject.calendarData());
            return calendar.getComponents(Component.VEVENT).stream()
                .map(VEvent.class::cast)
                .anyMatch(vEvent -> matchesBookingLink(vEvent, bookingLinkPublicId) && matchesSince(vEvent, since));
        } catch (Exception e) {
            LOGGER.warn("Skipping calendar object {} that could not be parsed", calendarObject.href(), e);
            return false;
        }
    }

    private boolean matchesBookingLink(VEvent vEvent, BookingLinkPublicId bookingLinkPublicId) {
        return EventParseUtils.getPropertyValueIgnoreCase(vEvent, BOOKING_LINK_PROPERTY)
            .filter(bookingLinkPublicId.value().toString()::equals)
            .isPresent();
    }

    private boolean matchesSince(VEvent vEvent, Optional<Instant> since) {
        return since.map(instant -> vEvent.getProperty(Property.DTSTAMP)
                .flatMap(EventParseUtils::parseTimeAsInstant)
                .filter(dtStamp -> !dtStamp.isBefore(instant))
                .isPresent())
            .orElse(true);
    }

    private Mono<Task.Result> deleteEvent(Username username, CalendarURL calendarUrl, Context context, String eventPathId) {
        return calDavClient.deleteCalendarEvent(username, calendarUrl, eventPathId)
            .doOnSuccess(any -> context.increaseDeleted())
            .thenReturn(Task.Result.COMPLETED)
            .onErrorResume(e -> {
                LOGGER.warn("Failed to delete event {} in calendar {} for user {}",
                    eventPathId, calendarUrl.asUri(), username.asString(), e);
                context.increaseFailed();
                return Mono.just(Task.Result.PARTIAL);
            });
    }
}
