/********************************************************************
 *  As a subpart of Twake Mail, this file is edited by Linagora.    *
 *                                                                  *
 *  https://twake-mail.com/                                         *
 *  https://linagora.com                                            *
 *                                                                  *
 *  This file is subject to The Affero Gnu Public License           *
 *  version 3.                                                      *
 *                                                                  *
 *  https://www.gnu.org/licenses/agpl-3.0.en.html                   *
 *                                                                  *
 *  This program is distributed in the hope that it will be         *
 *  useful, but WITHOUT ANY WARRANTY; without even the implied      *
 *  warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR         *
 *  PURPOSE. See the GNU Affero General Public License for          *
 *  more details.                                                   *
 ********************************************************************/

package com.linagora.calendar.saas.contact;

import java.io.IOException;
import java.util.Optional;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

public class CollectedContactUpdateCalculator {
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    Optional<byte[]> calculate(CollectedContact existingContact,
                               CollectedContact incomingContact) {
        try {
            ObjectNode existingContactData = toNormalizedContactData(existingContact);
            if (shouldMergeComplementaryIdentities(existingContact, incomingContact)) {
                return calculateMergedUpdate(existingContactData, incomingContact);
            }
            return calculateUpdateIfChanged(existingContactData, incomingContact);
        } catch (CollectedContact.CollectedContactException | IOException e) {
            throw new CollectedContactUpdateCalculationException("Unable to calculate collected contact update", e);
        }
    }

    private boolean shouldMergeComplementaryIdentities(CollectedContact existingContact,
                                                       CollectedContact incomingContact) {
        boolean existingHasEmail = existingContact.hasEmailAddress();
        boolean existingHasMatrixId = existingContact.hasMatrixId();
        boolean incomingHasEmail = incomingContact.hasEmailAddress();
        boolean incomingHasMatrixId = incomingContact.hasMatrixId();

        boolean shouldMergeMatrixIdIntoExistingEmail = existingHasEmail && incomingHasMatrixId && !incomingHasEmail;
        boolean shouldMergeEmailIntoExistingMatrixId = existingHasMatrixId && !existingHasEmail && incomingHasEmail && !incomingHasMatrixId;

        return shouldMergeMatrixIdIntoExistingEmail || shouldMergeEmailIntoExistingMatrixId;
    }

    private Optional<byte[]> calculateMergedUpdate(ObjectNode existingContactData,
                                                   CollectedContact incomingContact) throws IOException {
        ObjectNode incomingContactData = toNormalizedContactData(incomingContact);
        ObjectNode mergedContactData = existingContactData.deepCopy();
        // Incoming contacts always contain a UID, keeping the merged update on the same CardDAV resource.
        mergedContactData.setAll(incomingContactData);

        return calculateUpdateIfChanged(existingContactData, CollectedContact.parse(mergedContactData));
    }

    private Optional<byte[]> calculateUpdateIfChanged(ObjectNode existingContactData,
                                                      CollectedContact candidateContact) throws IOException {
        byte[] candidateVCard = candidateContact.toVCardAsBytes();
        // Conversion may add representational details, such as vCard groups for labels.
        ObjectNode canonicalCandidateData = toNormalizedContactData(CollectedContact.parse(candidateVCard));
        return existingContactData.equals(canonicalCandidateData) ? Optional.empty() : Optional.of(candidateVCard);
    }

    private ObjectNode toNormalizedContactData(CollectedContact contact) throws IOException {
        ObjectNode contactData = OBJECT_MAPPER.readValue(contact.toJson(), ObjectNode.class);
        // VCard2JSContact keeps the source VERSION as a raw property. Reapplying it would override
        // the vCard 4.0 version generated by JSContact2VCard.
        Optional<ArrayNode> normalizedVCardProps = Optional.ofNullable(contactData.get("vCardProps"))
            .filter(ArrayNode.class::isInstance)
            .map(ArrayNode.class::cast)
            .map(ArrayNode::deepCopy)
            .map(vCardProps -> vCardProps.removeIf(property -> property.isArray()
                && !property.isEmpty()
                && "version".equalsIgnoreCase(property.get(0).asText())));

        // PRODID identifies the serializer and does not affect contact semantics.
        ObjectNode normalizedContactData = contactData.deepCopy().without("vCardProps");
        normalizedContactData.remove("prodId");
        normalizedVCardProps
            .filter(vCardProps -> !vCardProps.isEmpty())
            .ifPresent(vCardProps -> normalizedContactData.set("vCardProps", vCardProps));
        return normalizedContactData;
    }

    static final class CollectedContactUpdateCalculationException extends RuntimeException {
        CollectedContactUpdateCalculationException(String message, Throwable cause) {
            super(message, cause);
        }
    }
}
